# Makefile for mock ML project

# Target for prediction
predict:
	echo "Running the predict script..."
	python src/predict.py

# Target for preprocessing
preprocess:
	echo "Running the preprocessing script..."
	python src/preprocess.py

# Target for building the Docker image
build-docker:
	echo "Building the Docker image..."
	docker build -t mock_ml_image .


